services:
  saucedemo-qa:
    build: .
    image: saucedemo-ui-tests
    container_name: saucedemo-ui-tests-qa
    environment:
      - PLAYWRIGHT_HEADLESS=1
    command: ["npx", "playwright", "test", "--project=qa-chrome"]
    volumes:
      - ./playwright-report:/app/playwright-report
